ALTER TABLE pedidos
  ADD COLUMN IF NOT EXISTS cep TEXT,
  ADD COLUMN IF NOT EXISTS endereco TEXT,
  ADD COLUMN IF NOT EXISTS cidade TEXT,
  ADD COLUMN IF NOT EXISTS estado TEXT,
  ADD COLUMN IF NOT EXISTS complemento TEXT,
  ADD COLUMN IF NOT EXISTS frete DECIMAL(10,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS metodo_envio TEXT DEFAULT 'pac',
  ADD COLUMN IF NOT EXISTS codigo_rastreio TEXT;
